//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQuizSonDeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullaniciBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullaniciBilgileri()
        {
            this.SoruKarti = new HashSet<SoruKarti>();
        }
    
        public int id { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string kullaniciAdi { get; set; }
        public string sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruKarti> SoruKarti { get; set; }
    }
}
