//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQuizSonDeneme.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcQuizYeniEntities : DbContext
    {
        public MvcQuizYeniEntities()
            : base("name=MvcQuizYeniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kullaniciBilgileri> kullaniciBilgileri { get; set; }
        public virtual DbSet<SoruKarti> SoruKarti { get; set; }
        public virtual DbSet<soruKategori> soruKategori { get; set; }
    }
}
